---
- name: Install and configure NGINX
  hosts: web
  become: true
  roles:
    - nginx

- name: Configure rsyslog
  hosts: log
  become: true
  roles:
    - rsyslog

- name: Install and configure Elasticsearch, Logstash, and Kibana
  hosts: elk
  become: true
  roles:
    - elk
