galaxy_info:
  author: alan
  description: Nginx install for Linux
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
      - 7
  galaxy_tags:
    - web
    - nginx
