---
- hosts: all
  become: true
  vars_files:
    - vars.yml
  tasks:

  - name: Install EPEL Repo package from standard repo
    yum:
      name: epel-release
      state: present

  - name: Install Kerberos workstation packages
    yum:
      name:
        - krb5-workstation
        - pam_krb5
      state: present

  - name: Install nfs-utils package
    yum:
      name: nfs-utils
      state: present

  - name: Copy hosts
    template: src=hosts.j2 dest=/etc/hosts owner=root group=root mode=0644

  - name: Copy krb5.conf
    template: src=krb5.conf.j2 dest=/etc/krb5.conf owner=root group=root mode=0644

- hosts: server
  become: true
  vars_files:
    - vars.yml
  tasks:

  - name: Install Kerberos server package
    yum:
      name: krb5-server
      state: present

  - name: Copy kdc.conf
    template: src=server/kdc.conf.j2 dest=/var/kerberos/krb5kdc/kdc.conf owner=root group=root mode=0600

  - name: Check if kdc already configured
    stat: path=/var/kerberos/krb5kdc/principal
    register: kdc_config

  - name: Initialise kdc
    shell: /usr/sbin/kdb5_util create -s -P {{ kdc_pass }}
    when: kdc_config.stat.exists == false

  - name: Create admin user
    shell: /usr/sbin/kadmin.local -q "addprinc -pw {{ kdc_pass }} root/admin"

  - name: Start services krb5kdc kadmin
    service: name={{ item }} state=started enabled=yes
    with_items: 
      - krb5kdc
      - kadmin

  - name: Add principal for host server.{{ realm }}
    shell: /usr/sbin/kadmin.local -q "addprinc -pw {{ kdc_pass }} -randkey host/server.{{ realm }}"

  - name: Add host server.{{ realm }}
    shell: /usr/sbin/kadmin.local -q "ktadd host/server.{{ realm }}"

  - name: Add principal for nfs server.{{ realm }}
    shell: /bin/kadmin -w {{ kdc_pass }} -q "addprinc -randkey nfs/server.{{ realm }}"

  - name: Add nfs server.{{ realm }}
    shell: /bin/kadmin -w {{ kdc_pass }} -q "ktadd nfs/server.{{ realm }}"

  - name: Create directory for nfs export
    file: path=/mnt/nfs_share state=directory owner=nfsnobody group=nobody mode=0755

  - name: Copy exports
    copy: src=server/exports dest=/etc/ owner=root group=root mode=0644

  - name: Start nfs-server
    service:
      name: nfs-server
      state: started
      enabled: yes

  - name: Add firewalld rules for nfs server, kerberos, kadmin
    firewalld: service={{ item }} state=enabled permanent=yes
    with_items: 
      - nfs
      - mountd
      - rpc-bind
      - kerberos
      - kadmin

  - name: Restart firewalld
    service:
      name: firewalld
      state: restarted
      enabled: yes


- hosts: client
  become: true
  vars_files:
    - vars.yml
  tasks:

  - name: Add principal for host client.{{ realm }}
    shell: /bin/kadmin -p root/admin@{{ realm|upper }} -w {{ kdc_pass }} -q "addprinc -randkey host/client.{{ realm }}"

  - name: Add host client.{{ realm }}
    shell: /bin/kadmin -p root/admin@{{ realm|upper }} -w {{ kdc_pass }} -q "ktadd host/client.{{ realm }}"

  - name: Add principal for nfs client.{{ realm }}
    shell: /bin/kadmin -p root/admin@{{ realm|upper }} -w {{ kdc_pass }} -q "addprinc -randkey nfs/client.{{ realm }}"

  - name: Add nfs client.{{ realm }}
    shell: /bin/kadmin -p root/admin@{{ realm|upper }} -w {{ kdc_pass }} -q "ktadd nfs/client.{{ realm }}"

  - name: Create directory for mount nfs share
    file: path=/mnt/nfs_share state=directory owner=nfsnobody group=nobody mode=0755

  - name: Enable nfs-client.target
    systemd:
      name: nfs-client.target
      state: restarted
      enabled: yes

  - name: Add nfs_share to fstab
    lineinfile:
      path: /etc/fstab
      line: "server.{{ realm }}:/mnt/nfs_share /mnt/nfs_share nfs vers=3,soft,timeo=100,_netdev,rw,sec=krb5 0 0"

  - name: Mount all filesystems
    command: mount -a
