---
- name: Install EPEL Repo package from standard repo
  yum:
    name: epel-release
    state: present

- name: Install nginx package from epel repo
  yum:
    name: nginx
    state: present

- name: Copy modified index.html
  template: src=index.html.j2 dest=/usr/share/doc/HTML/index.html owner=root group=root mode=0755

- name: Copy nginx config file
  copy: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify:
    - restart nginx

- name: Register web service in consul
  copy: src=web.json dest=/etc/consul.d/ owner=consul group=consul mode=0640
  notify:
    - restart consul
