# -*- mode: ruby -*-
# vim: set ft=ruby :

MACHINES = {
  :routerA => {
	:box_name => "centos/7",
	:net => [
	    {ip: '192.168.255.1', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "linkAB", neighbor: "192.168.255.2", cost: 10},
	    {ip: '192.168.255.10', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "linkCA", neighbor: "192.168.255.9", cost: 20},
	    {ip: '172.16.0.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "netA", neighbor: "", cost: ""},
	]
  },

  :routerB => {
	:box_name => "centos/7",
	:net => [
	    {ip: '192.168.255.2', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "linkAB", neighbor: "192.168.255.1", cost: 10},
	    {ip: '192.168.255.5', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "linkBC", neighbor: "192.168.255.6", cost: 10},
	    {ip: '172.16.1.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "netB", neighbor: "", cost: ""},
	]
  },

  :routerC => {
	:box_name => "centos/7",
	:net => [
	    {ip: '192.168.255.6', adapter: 2, netmask: "255.255.255.252", virtualbox__intnet: "linkBC", neighbor: "192.168.255.5", cost: 20},
	    {ip: '192.168.255.9', adapter: 3, netmask: "255.255.255.252", virtualbox__intnet: "linkCA", neighbor: "192.168.255.10", cost: 10},
	    {ip: '172.16.2.1', adapter: 4, netmask: "255.255.255.0", virtualbox__intnet: "netC", neighbor: "", cost: ""},
	]
  },

}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

    config.vm.define boxname do |box|

	box.vm.box = boxconfig[:box_name]
	box.vm.host_name = boxname.to_s

	boxconfig[:net].each do |ipconf|
	  box.vm.network "private_network", ipconf
	end

	if boxconfig.key?(:public)
	  box.vm.network "public_network", boxconfig[:public]
	end

	box.vm.provider :virtualbox do |vb|
	    vb.customize ["modifyvm", :id, "--memory", "256"]
	end

	box.vm.provision "shell", inline: <<-SHELL
	  mkdir -p ~root/.ssh
	  cp ~vagrant/.ssh/auth* ~root/.ssh
	SHELL

	box.vm.provision "ansible" do |ansible|
	    ansible.compatibility_mode = "2.0"
	    ansible.playbook = "routing.yml"
	    ansible.become = "true"
	    ansible.extra_vars = {
		vagrant_vars: {
		    nets: boxconfig[:net]
		}
	    }
	end

    end

  end

end
