---
- hosts: all
  become: true
  tasks:

  - name: install EPEL Repo package from standard repo
    yum:
      name: epel-release
      state: present

  - name: install OpenVPN, bridge-utils and utils
    yum:
      name:
        - openvpn
        - bridge-utils
        - mc
        - tcpdump
      state: present


- hosts: server
  become: true
  tasks:

  - name: copy openvpn files
    copy: src={{ item }} dest=/etc/openvpn/server/
    with_fileglob:
      - "{{ ansible_hostname }}/openvpn/*"

  - name: copy bridge config for tap
    copy: src=server/ifcfg-br0 dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=0644

  - name: add route to client1 via int_net
    command: ip route replace 172.16.1.100/32 dev eth1

  - name: add route to client2 via int_net
    command: ip route replace 172.16.2.100/32 dev eth1

  - name: restart NetworkManager
    systemd:
      name: NetworkManager
      state: restarted

  - name: restart openvpn-tap
    systemd:
      name: openvpn-server@server-tap
      state: restarted

  - name: restart openvpn-tun
    systemd:
      name: openvpn-server@server-tun
      state: restarted

- hosts: client*
  become: true
  tasks:

  - name: add route to server via int_net
    command: ip route replace 192.168.254.100/32 dev eth1

  - name: copy bridge config
    copy: src="{{ ansible_hostname }}/ifcfg-br0" dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=0644

  - name: copy openvpn files
    copy: src={{ item }} dest=/etc/openvpn/client/
    with_fileglob:
      - "{{ ansible_hostname }}/openvpn/*"

  - name: restart NetworkManager
    systemd:
      name: NetworkManager
      state: restarted

  - name: restart openvpn
    systemd:
      name: openvpn-client@client
      state: restarted
