---
- hosts: all
  become: true
  tasks:

  - name: install EPEL Repo package from standard repo
    yum:
      name: epel-release
      state: present

  - name: install OpenVPN, bridge-utils and utils
    yum:
      name:
        - openvpn
        - bridge-utils
        - mc
        - tcpdump
      state: present

  - name: enable ipv4 forwarding
    sysctl:
      name: net.ipv4.conf.all.forwarding
      value: '1'
      sysctl_set: yes
      reload: yes


- hosts: server
  become: true
  tasks:

  - name: install OpenConnect VPN Server
    yum:
      name: ocserv
      state: present

  - name: copy openvpn files
    copy: src={{ item }} dest=/etc/openvpn/server/ mode=preserve
    with_fileglob:
      - "{{ ansible_hostname }}/openvpn/*"

  - name: copy ocserv files
    copy: src={{ item }} dest=/etc/ocserv/ mode=preserve
    with_fileglob:
      - "{{ ansible_hostname }}/ocserv/*"

  - name: copy bridge config for tap
    copy: src=server/ifcfg-br0 dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=0644

  - name: add route to client1 via int_net
    command: ip route replace 172.16.1.100/32 dev eth1

  - name: add route to client2 via int_net
    command: ip route replace 172.16.2.100/32 dev eth1

  - name: restart NetworkManager
    systemd:
      name: NetworkManager
      state: restarted

#  Failed to import the required Python library (policycoreutils-python)
#  - name: add additional tcp port 1195 for openvpn-ras in SELinux
#    seport:
#      ports: 1195
#      proto: tcp
#      setype: openvpn_port_t
#      state: present

  - name: Put SELinux in permissive mode, logging actions that would be blocked.
    selinux:
      policy: targeted
      state: permissive

  - name: restart ocserv
    systemd:
      name: ocserv
      state: restarted

  - name: restart openvpn-tap
    systemd:
      name: openvpn-server@server-tap
      state: restarted

  - name: restart openvpn-tun
    systemd:
      name: openvpn-server@server-tun
      state: restarted

  - name: restart openvpn-ras
    systemd:
      name: openvpn-server@server-ras
      state: restarted

- hosts: client*
  become: true
  tasks:

  - name: add route to server via int_net
    command: ip route replace 192.168.254.100/32 dev eth1

  - name: copy bridge config
    copy: src="{{ ansible_hostname }}/ifcfg-br0" dest=/etc/sysconfig/network-scripts/ owner=root group=root mode=0644

  - name: copy openvpn files
    copy: src={{ item }} dest=/etc/openvpn/client/
    with_fileglob:
      - "{{ ansible_hostname }}/openvpn/*"

  - name: restart NetworkManager
    systemd:
      name: NetworkManager
      state: restarted

  - name: restart openvpn
    systemd:
      name: openvpn-client@client
      state: restarted
