---
- name: restart nginx
  systemd:
    name: nginx
    state: "{{ nginx_systemd_state }}"
    enabled: "{{ nginx_systemd_enabled }}"

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded

# Restart auditd via service command (systemctl not working. RefuseManualStop=yes in systemd unit)
- name: restart auditd
  command: /sbin/service auditd restart

- name: restart rsyslog
  systemd:
    name: rsyslog
    state: restarted
    enabled: yes

- name: restart filebeat
  systemd:
    name: filebeat
    state: restarted
    enabled: yes
