---
- name: Install rpm packages for ipa client
  yum:
    name:
      - ipa-client
    state: present
  tags:
    - ipa-client

- name: Generate /etc/hosts file
  template:
    src=etc/hosts.j2
    dest=/etc/hosts
  tags:
    - hosts

- name: Configure ipa client
  command: ipa-client-install --hostname={{ ansible_fqdn }} \
                              --domain={{ ansible_domain }} \
                              --server={{ ipa_server }} \
                              --realm={{ ansible_domain | upper }} \
                              --principal={{ ipa_admin_principal }} \
                              --password={{ ipa_admin_password }} \
                              --mkhomedir \
                              --unattend
  args:
    creates: /etc/ipa/default.conf
  tags:
    - ipa-client

- include: ipa-user-create.yml
