---
- name: Install rpm packages for ipa client
  yum:
    name:
      - ipa-client
    state: present
  tags:
    - ipa-client

- name: Generate /etc/hosts file
  template:
    src=etc/hosts.j2
    dest=/etc/hosts
  tags:
    - hosts

- name: Configure ipa client
  command: ipa-client-install --hostname={{ ansible_fqdn }}
                              --domain={{ ansible_domain }}
                              --server={{ ipa_server }}
                              --realm={{ ansible_domain | upper }}
                              --principal={{ ipa_admin_principal }}
                              --password={{ ipa_admin_password }}
                              --mkhomedir
                              --unattend
  args:
    creates: /etc/ipa/default.conf
  tags:
    - ipa-client

- name: Generate rsa ssh keys pair
  openssh_keypair:
    path: /root/.ssh/id_rsa_jonh_smith
    size: 2048
    comment: johh.smith
  register: sshkey
  tags:
    - ipa-user

- name: Adding test user Jonh Smith
  ipa_user:
    name: john.smith
    state: present
    givenname: John
    sn: Smith
    sshpubkey:
      - "{{ sshkey.public_key }}"
    ipa_host: "{{ ipa_server }}"
    ipa_user: "{{ ipa_admin_principal }}"
    ipa_pass: "{{ ipa_admin_password }}"
  tags:
    - ipa-user
