version: '3'

services:
  server1:
    image: mysql/mysql-server:8.0.18
    env_file:
      - server.env
    ports:
      - "33061:3306"
    command: ["mysqld","--server_id=1","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin",
      "--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64",
      "--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  server2:
    image: mysql/mysql-server:8.0.18
    env_file:
      - server.env
    ports:
      - "33062:3306"
    command: ["mysqld","--server_id=2","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin",
      "--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64",
      "--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  server3:
    image: mysql/mysql-server:8.0.18
    env_file:
      - server.env
    ports:
      - "33063:3306"
    command: ["mysqld","--server_id=3","--binlog_checksum=NONE","--gtid_mode=ON","--enforce_gtid_consistency=ON","--log_bin",
      "--log_slave_updates=ON","--master_info_repository=TABLE","--relay_log_info_repository=TABLE","--transaction_write_set_extraction=XXHASH64",
      "--user=mysql","--skip-host-cache","--skip-name-resolve", "--default_authentication_plugin=mysql_native_password"]

  shell:
    env_file:
      - shell.env
    image: halaram/mysql-shell:0.1
    volumes:
      - ./scripts/:/scripts/:z
    depends_on:
      - server1
      - server2
      - server3
    stdin_open: true
    tty: true

  router:
    env_file:
      - router.env
    image: mysql/mysql-router:8.0.18
    ports:
      - "6446:6446"
    depends_on:
      - server1
      - server2
      - server3
      - shell
    restart: on-failure
