---
- name: restart nginx
  systemd:
    name: nginx
    state: "{{ nginx_systemd_state }}"
    enabled: "{{ nginx_systemd_enabled }}"

- name: reload nginx
  systemd:
    name: nginx
    state: reloaded
