---
- name: PAM | Create bash script for pam_exec.so
  template:
    src: test_login.sh.j2
    dest: /usr/local/bin/test_login.sh
    owner: root
    group: root
    mode: 0755
  tags:
    - pam-configuration


- name: PAM | Insert a rule pam_exec.so to ssh pam 
  pamd:
    name: sshd
    type: account
    control: required
    module_path: pam_nologin.so
    new_type: account
    new_control: required
    new_module_path: pam_exec.so
    module_arguments: /usr/local/bin/test_login.sh
    state: after
  tags:
    - pam-configuration

- name: PAM | Create group 'admin'
  group:
    name: admin
    state: present
  tags:
    - pam-test

- name: PAM | Add the user 'admin1' with password '123'
  user:
    name: admin1
    group: admin
    password: $1$ZZANpdlZ$SJ3TbYZjJwEpMQszub1UW0
  tags:
    - pam-test

- name: PAM | Add the user 'user1' with password '123'
  user:
    name: user1
    password: $1$ZZANpdlZ$SJ3TbYZjJwEpMQszub1UW0
  tags:
    - pam-test
