version: "3"

services:
  nginx:
    image: halaram/nginx
    ports:
      - "80:80"
    volumes:
      - /vagrant/docker/log:/var/log/nginx:Z
      - /vagrant/docker/www:/www:z
    networks:
      - www
    links:
      - php
  php:
    image: halaram/php-fpm
    volumes:
      - /vagrant/docker/www:/www:z
    networks:
      - www

networks:
  www:
