galaxy_info:
  author: alan
  description: Rsyslog server configure for Linux
  license: MIT
  min_ansible_version: 2.4
  platforms:
    - name: EL
      versions:
      - 7
  galaxy_tags:
    - logging
    - rsyslog
