# -*- mode: ruby -*-
# vim: set ft=ruby :
home = ENV['HOME']


MACHINES = {
  :otuslinux => {
        :box_name => "centos/7",
        :ip_addr => '192.168.11.101',
	:disks => {
		:sata1 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata1.vdi',
                    :size => 250,
                    :port => 1
		},
		:sata2 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata2.vdi',
                    :size => 250,
                    :port => 2
                },
                :sata3 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata3.vdi',
                    :size => 250,
                    :port => 3
                },
                :sata4 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata4.vdi',
                    :size => 250,
                    :port => 4
                },
                :sata5 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata5.vdi',
                    :size => 250,
                    :port => 5
                },
                :sata6 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata6.vdi',
                    :size => 250,
                    :port => 6
                },
                :sata7 => {
                    :dfile => '/mnt/share/VirtualBox VMs/disks/sata7.vdi',
                    :size => 250,
                    :port => 7
                }

	}
    },
}

Vagrant.configure("2") do |config|

  MACHINES.each do |boxname, boxconfig|

      config.vm.define boxname do |box|

          box.vm.box = boxconfig[:box_name]
          box.vm.host_name = boxname.to_s

          #box.vm.network "forwarded_port", guest: 3260, host: 3260+offset

          box.vm.network "private_network", ip: boxconfig[:ip_addr]

          box.vm.provider :virtualbox do |vb|
            	vb.customize ["modifyvm", :id, "--memory", "256"]
                needsController = false
		boxconfig[:disks].each do |dname, dconf|
			unless File.exist?(dconf[:dfile])
				vb.customize ['createhd', '--filename', dconf[:dfile], '--variant', 'Fixed', '--size', dconf[:size]]
                                needsController =  true
                        end

		end
                if needsController == true
                    vb.customize ["storagectl", :id, "--name", "SATA", "--add", "sata" ]
                    boxconfig[:disks].each do |dname, dconf|
                        vb.customize ['storageattach', :id,  '--storagectl', 'SATA', '--port', dconf[:port], '--device', 0, '--type', 'hdd', '--medium', dconf[:dfile]]
                    end
                end
          end

          box.vm.provision "shell", inline: <<-SHELL
	      mkdir -p ~root/.ssh
              cp ~vagrant/.ssh/auth* ~root/.ssh
	      yum install -y mdadm smartmontools hdparm gdisk
	      mdadm --zero-superblock /dev/sd{b,c,d,e,f,g,h} 2> /dev/null
	      mdadm --create /dev/md0 --verbose --level=6 --raid-devices=7 /dev/sd{b,c,d,e,f,g,h}
	      echo "DEVICE partitions" > /etc/mdadm.conf
	      mdadm --detail --brief /dev/md0 >> /etc/mdadm.conf
  	  SHELL

      end
  end
end

